/**
 * CaseIntel — Evidence API
 *
 * Typed wrappers for all evidence-related FastAPI endpoints.
 * The base client auto-normalises snake_case → camelCase.
 */

import { apiFetch } from './client';
import type { Evidence } from '../types';

// ── Chain-of-custody entry ────────────────────────────────────────────────
export interface ChainEntry {
  action: string;
  actor: string;
  timestamp: string;
  note?: string;
  sha256?: string;
}

export interface ChainOfCustody {
  evidenceId: string;
  chain: ChainEntry[];
}

// ── Request shape for POST /api/evidence/ ────────────────────────────────
export interface EvidenceCreatePayload {
  investigationId: string;
  cameraId: string;
  type: string;
  primaryEntityId: string;
  secondaryEntityId?: string;
  eventId: string;
  confidence?: number;
  description: string;
  isKeyEvidence?: boolean;
}

// ── Response wrapper from GET /api/evidence/ ─────────────────────────────
interface ListResponse {
  evidence: Evidence[];
  total: number;
}

// ── Endpoints ─────────────────────────────────────────────────────────────

/**
 * GET /api/evidence/?investigation_id=
 * Returns the evidence list for a given investigation (or all if omitted).
 */
export async function getEvidence(investigationId?: string): Promise<Evidence[]> {
  const qs = investigationId ? `?investigation_id=${encodeURIComponent(investigationId)}` : '';
  const data = await apiFetch<ListResponse>(`/api/evidence/${qs}`);
  return data.evidence;
}

/**
 * GET /api/evidence/{id}
 */
export async function getEvidenceItem(evidenceId: string): Promise<Evidence> {
  return apiFetch<Evidence>(`/api/evidence/${evidenceId}`);
}

/**
 * POST /api/evidence/
 * Creates a new evidence record. SHA-256 is auto-generated by the backend.
 */
export async function createEvidence(payload: EvidenceCreatePayload): Promise<Evidence> {
  return apiFetch<Evidence>('/api/evidence/', { method: 'POST', body: payload });
}

/**
 * GET /api/evidence/{id}/chain-of-custody
 */
export async function getChainOfCustody(evidenceId: string): Promise<ChainOfCustody> {
  return apiFetch<ChainOfCustody>(`/api/evidence/${evidenceId}/chain-of-custody`);
}
